  # This is the shift-api deployment manifest section.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shift-api-deployment
  labels:
    app: shift-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shift-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: shift-api
    spec:
      containers:
      - name: shift-api
        image: wordpress:php8.2
        env:
        - name: WORDPRESS_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: database-configmap
              key: shift_database_url
        - name: WORDPRESS_DB_USER
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: db_user_name
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: db_user_password
        - name: WORDPRESS_DB_NAME
          valueFrom:
            secretKeyRef:
              name: database-secrets
              key: db_root_name
        resources: {}     # other resources can be further defined here


---
  # This is the shift-api Load Balancer Service manifest.
apiVersion: v1
kind: Service
metadata:
  name: shift-api-service
spec:
  type: LoadBalancer
  selector:
    app: shift-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---
  # This is the shift-api Horizontal Pod Autoscaler manifest.
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: shift-api-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: shift-api-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70